[build]
  base = "frontend"
  command = "npm install && npx ng build --configuration production"
  publish = "frontend/dist/valentine-game"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
